export const plansAT = {
  GET_USER_PLANS: "GET_USER_PLANS",
  // HIDE_USER_PLANS: "HIDE_USER_PLANS",
  PLANS_SEND_ERROR: "PLANS_SEND_ERROR",
  PLANS_SEND: "PLANS_SEND",
  PLANS_UPLOADED: "PLANS_UPLOADED",
  SEND_USER_PLANS: "SEND_USER_PLANS",
  UPDATE_USER_PLANS: "UPDATE_USER_PLANS",
  PLANS_UPDATED: "PLANS_UPDATED",
  DELETE_USER_PLAN: "DELETE_USER_PLAN",
}
