export const userAT = {
  CREATE_USER: "CREATE_USER",
  NEW_USER: "NEW_USER",
  REGISTRATION_FAILED: "REGISTRATION_FAILED",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN: "LOGIN",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT: "LOGOUT",
  CLEAR_STATE: "CLEAR_STATE",
}
